#!/bin/bash
#PBS -m abe
#PBS -N V2D
#PBS -q standard
##PBS -t 0-9

#PBS -o output/$PBS_JOBNAME.o$PBS_JOBID
#PBS -e output/$PBS_JOBNAME.e$PBS_JOBID

# num_Pe=10
# num_s=1

couplingMode='C'
initMode='R'
intMethod='E'

N=10000
phi=0.1

##Pe_arr=($(seq 2 2.0 20))
##Pe=${Pe_arr[$(($PBS_ARRAYID / $num_Pe))]}
Pe=3.0

##seed_arr=($(seq 1 1 10))
##seed=${seed_arr[$(($PBS_ARRAYID / $num_Pe % $num_s))]}
seed=1

xTy=1.0

K_AVG=1.0
K_STD=0.0

dT=0.01
DT=10.0
DTex=100
eqT=0.0
simulT=1000

cd $PBS_O_WORKDIR

bash runV.sh $N $phi $Pe $seed $xTy $initMode $couplingMode $K_AVG $K_STD $dT $DT $DTex $eqT $simulT

cd $PBS_O_WORKDIR/analysis
python3 main.py $mode $N $phi $Pe $K_AVG $xTy $seed